openapi: 3.0.0
servers:
    - url: 'http://tbd.swagger.io'
      description: ''
info:
    description: >-
        This is a prototype for the Student-Wellbeing project required for
        University of Reading module CS3IP18.
    version: 1.0.0
    title: Swagger Student Wellbeing
    termsOfService: 'http://swagger.io/terms/'
    contact:
        email: gv009864@reading.ac.uk
        name: Tarnjot Singh Virdee
tags:
    - name: survey
      description: Experts curating surveys
      externalDocs:
          description: Find out more
          url: 'http://swagger.io'
paths:
    /survey: {}
    '/survey/{surveyId}':
        put:
            summary: Update a specified survey
            description: Update a specified survey
            parameters:
                - name: surveyId
                  in: path
                  required: true
                  schema:
                      type: string
                  description: ''
            operationId: ''
            responses:
                '200':
                    description: Description
                    content:
                        change/me:
                            schema: {}
                '201':
                    description: Description
                    content:
                        change/me:
                            schema: {}
                '202':
                    description: Description
                    content:
                        change/me:
                            schema: {}
            requestBody:
                content:
                    application/json:
                        schema: {}
                required: true
                description: JSON body specifying how to update the specified server.
        get:
            summary: ''
            description: ''
            parameters:
                - name: surveyId
                  in: path
                  required: true
                  schema:
                      type: string
            operationId: ''
            responses:
                '200':
                    description: Description
                    content:
                        application/json:
                            schema: {}
                '201':
                    description: Description
                    content:
                        application/json:
                            schema: {}
                '202':
                    description: Description
                    content:
                        application/json:
                            schema: {}
        delete:
            summary: ''
            description: ''
            parameters:
                - name: surveyId
                  in: path
                  required: true
                  schema:
                      type: string
            operationId: ''
            responses:
                default:
                    description: Default response
externalDocs:
    description: See AsyncAPI example
    url: 'https://mermade.github.io/shins/asyncapi.html'


#------------------------------
# Components allowing for code
# reuse where required
#------------------------------
components:
    #---------------------
    # Reusable schemas
    #---------------------
    schemas:
        Survey:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
    securitySchemes:
        api_key:
            type: apiKey
            name: api_key
            in: header
        surveys_auth:
            type: oauth2
            flows:
                implicit:
                    authorizationUrl: 'http://tbd.swagger.io/oauth/dialog'
                    scopes:
                        'write:surveys': modify surveys
                        'read:surveys': read surveys
    links: {}
    callbacks: {}
security: []
